spring:
  redis:
    ##redis-cache缓存时间，单位(分)
    entityttl: 60
    database: 0 #选择下标几的库
    host: 127.0.0.1 #redis服务器IP地址
    port: 6379 #redis服务器端口号
    timeout: 20000 # 连接超时时长（毫秒）
    sentinel:
      master: mymaster #哨兵名称
      nodes: #redis集群IP地址
        - 127.0.0.1:7000
        - 127.0.0.1:7001
        - 127.0.0.1:7002
    jedis:
      pool:
        max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        max-wait: 3000s # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 5 # 连接池中的最小空闲连接