#@Author 邋遢龘鵺 本地
spring:
  project:
    name: demo_framework_backstage_local
  file:
    #上传路径存储目录
    upload-dir: H:\demo_framework_backstage_local
  security:
    #登录记住我选择，(单位：秒)=1天
    remember-me-time: 86400
    #token令牌有效天数,单位天
    token-valid-days: 15
    #配置角色不验证权限全部放过集合
    auth-list: xxx,system_ultra_admin
  datasource:
    read-one:
      name: read
      driverClassName: com.mysql.cj.jdbc.Driver #?useSSL=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8,数据连接8.X版本jar
      jdbcUrl: jdbc:mysql://localhost:3306/demoframework?allowMultiQueries=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
      #      driverClassName: com.mysql.jdbc.Driver #?useSSL=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8,数据连接5.X版本jar
      #      jdbcUrl: jdbc:mysql://127.0.0.1:3306/demoframework?useSSL=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
      username: root
      password: 123456
    write-one:
      name: write #?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
      driverClassName: com.mysql.cj.jdbc.Driver #?useSSL=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8,数据连接8.X版本jar
      jdbcUrl: jdbc:mysql://localhost:3306/demoframework?allowMultiQueries=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
      #      driverClassName: com.mysql.jdbc.Driver #?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false,数据连接5.X版本jar
      #      jdbcUrl: jdbc:mysql://127.0.0.1:3306/demoframework?useSSL=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
      username: root
      password: 123456
    initial-Size: 5
    min-Idle: 5
    max-Active: 20
    max-Wait: 60000
    time-Between-Eviction-Runs-Millis: 60000
    minEvictableIdle-Time-Millis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#    type: com.alibaba.druid.pool.DruidDataSource
#  transaction:
#    rollback-on-commit-failure: true
server:
  #启动端口号配置
  port: 8082
  tomcat:
    uri-encoding: UTF-8
rocketmq:
  name-server: 114.117.175.169:9876
  producer:
    group: local-demo-group
    access-key: rocketmq2
    secret-key: 12345678
  consumer:
    topic: local-demo-xxxx
    selectorExpression: "*"
    group: local-demo-group

logging:
  file:
    path: G:\install\idea-save\gitee\log
    #    path: /test/jdk/log/XXXX-web-backstage
    name: G:\install\idea-save\gitee\log\demo_framework_backstage_local.log
  level:
    jdbc:
      audit: off
      resultset: off
      sqltiming: off
    com:
      framework:
        mapper: debug #打印sql语句
    org:
      springframework:
        web: error # 打印请求异常
    root: INFO
custom:
  ignored:
    init-ignore-url: #初始化不拦截URL
      - /
      - /login
      - /login/page
      - /favicon.ico
      - /default/captcha
    ignore-url: #不拦截URL
      - /test
  ignored-data-role-auth:
    #配置角色不验证数据权限全部放过集合
    auth-list:
      - market_manage
  ignored-role-auth:
    #配置角色不验证权限全部放过集合
    auth-list:
      - system_ultra_admin
