spring:
  redis:
    ##redis-cache缓存时间，单位(分)
    entityttl: 60
    database: 0 #选择下标几的库
#    host: 127.0.0.1 #redis服务器IP地址
#    port: 6379 #redis服务器端口号
    timeout: 20000s # 连接超时时长（毫秒）
#    password: 123456
    cluster:
      #redis集群IP地址
      nodes: 127.0.0.1:7000,127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005
#        - 127.0.0.1:7000
#        - 127.0.0.1:7001
#        - 127.0.0.1:7002
#        - 127.0.0.1:7003
#        - 127.0.0.1:7004
#        - 127.0.0.1:7005
      max-redirects: 3 # 获取失败 最大重定向次数
      timeout: 20000 # 连接超时时长（毫秒）
      #使用jedis：当多线程使用同一个连接时，是线程不安全的。所以要使用连接池，为每个jedis实例分配一个连接。
      #使用Lettuce：当多线程使用同一连接实例时，是线程安全的。 redis-server.exe redis.windows.conf
#    lettuce:
    jedis:
      pool:
        max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        max-wait: 3000s # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 5 # 连接池中的最小空闲连接

