spring:
  redis:
    ##redis-cache缓存时间，单位(分)
    entityttl: 60
    # 单机配置
    # Redis数据库索引（默认为0）
    database: 0
    #redis服务器IP地址
    host: 106.54.42.143
    #redis服务器端口号
    port: 6379
    #密码设置
    password: test123456!
    #连接超时时间（毫秒）
    timeout: 20000s
    #连接池配置
    jedis:
      pool:
        #最大连接数（使用负值表示没有限制）
        max-active: 8
        #最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000s
        #最大空闲连接
        max-idle: 8
        #最小空闲连接
        min-idle: 0